### ISSUE TITLE
“Silently” fallback to comparing SHA when using `latest`

### ISSUE THREAD

**Issue by johanfleury** [jetstack/version-checker#10]
When a container image uses the `latest` tag, `version-checker` should fallback to comparing SHA “silently” (the log level should be relaxed).

At the moment, logs are filled with:

```
time="2020-08-18T18:38:35Z" level=warning msg="image using \"latest\" tag, comparing image SHA \"sha256:530e471dba7ee6995a230b43a1c8db4404873fb0402469397c8674dcf920d59f\"" container=foo
module=controller name=foobar-0 namespace=foobar
```

I believe this message should be emitted with log level `debug`.

**Comment by JoshVanL** [comment]
Yes, I agree. This is no good

/assign
