### ISSUE TITLE
Please add Pod Labels in Helm Chart

### ISSUE THREAD

**Issue by hkailantzis** [jetstack/version-checker#109]
Hi there,

If could you add Pod Labels in the Helm Chart, and also an option to disable ClusterRole And ClusterRoleBinding, that would be great, as it a hard requirement for us to be able to use it, since we just need to access images running on namespace level only.

Thanks in advance!.

**Comment by davidcollom** [comment]
Pull Requests are always welcome! 😄  but could you be a little more specific on _what_ labels you're expecting to see on the pods deployed from the helm chart?

**Comment by hkailantzis** [comment]
hi @davidcollom ,thanks for your reply... any custom pod labels, ie a yaml block that any user could just define whatever is necessary... just as an example:

https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/templates/deployment.yaml#L20C17-L20C17
