### ISSUE TITLE
version-checker fails with nginx-ingress controller new registry

### ISSUE THREAD

**Issue by johanfleury** [jetstack/version-checker#11]
I’m not sure why but `version-checker` seems to fail on the nginx-ingress controller image:

```
time="2020-08-18T18:38:33Z" level=error msg="error syncing 'nginx-ingress-9bbd564fc-8ktdv/nginx-ingress': failed to sync pod nginx-ingress-9bbd564fc-8ktdv/nginx-ingress: failed to test container image
\"nginx-ingress-controller\": \"us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller\": no tags found for given image URL: \"us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller\", requeuing"       
module=controller
```

`us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller` is the new official image according to [ingress-nginx release notes for version 0.34.0](https://github.com/kubernetes/ingress-nginx/blob/master/Changelog.md#0340).

I believe the issue might be that some images have been published without a tag in that registry.

**Comment by JoshVanL** [comment]
At first I thought this was because it has the version and sha on the image, though it looks like it has the correct URL.

https://github.com/jetstack/version-checker/blob/d3308c0d8b78c787c88187287b9a9f13efe04118/pkg/controller/sync.go#L226

I'll need to investigate a bit more what's going on here, but I'm fairly certain this is a bug.

/assign

**Comment by johanfleury** [comment]
I forgot to tell, I’m not specifying the sha256 of the image in my deployment, only the tag:

```
k get deployments.apps -n nginx-ingress -o wide
NAME                       READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS                 IMAGES                                                          SELECTOR
nginx-ingress              1/1     1            1           9d    nginx-ingress-controller   us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1   app.kubernetes.io/instance=nginx-ingress,app.kubernetes.io/name=nginx-ingress
```

**Comment by JoshVanL** [comment]
Okay, thanks for the heads-up!

The URL parsing to determine the client + repo/image is quite fragile, and should be improved. Believe this is where the issue is coming from

**Comment by anchaljain30** [comment]
@JoshVanL Does this feature not support ghcr.io and public ecr repositories? Because I am facing the same issue on both of them, other repositories are working fine.
