### ISSUE TITLE
Provide GHCR example

### ISSUE THREAD

**Issue by jwitko** [jetstack/version-checker#124]
Hey!  Thank you for making this terrific application.  It's really useful. 

I'm getting some errors in my use-case about unauthorized attempts to access the `api.github.com` URL for checking image tags.  It looks like this cannot be accessed unauthenticated in v4 of the GitHub API spec (apparently it could be in v3?).  

I'm looking for an example of how to configure a GHCR account.  I see the PR where support was implemented but not really sure how to enable it via the helm chart.

**Comment by davidcollom** [comment]
Hey, Thanks for creating this, it looks like the GHCR support has been missing from the helm chart - I'll take a look at getting this implemented.
