### ISSUE TITLE
Allow for excluding specific containers 

### ISSUE THREAD

**Issue by jwitko** [jetstack/version-checker#125]
When enabling version-checker to check all applications there should be a way to exclude specific containers.  This would be extremely useful for containers hosted in places that version-checker does not yet support.

**Comment by davidcollom** [comment]
This can already be achieved by adding Annotation: `enable.version-checker.io/sidecar=false` on the pod that has a container name `sidecar`.

**Comment by jwitko** [comment]
Thank you I must've missed that.
