### ISSUE TITLE
Implementing Artifactory

### ISSUE THREAD

**Issue by wiardvanrij** [jetstack/version-checker#14]
First of all, thank you for this project. It's awesome. 

For our stack I'm eager to combine this with Artifactory. I would not mind investing some time to get started on such feature. Yet I'm not sure if there is already a plan for this or any roadmap? 

Basically, this "issue" is my request on how to help :)

**Comment by JoshVanL** [comment]
Hi @wiardvanrij, awesome!

Yeah, that would be great :smile: 

You will need to create a new image client which implements this interface.

https://github.com/jetstack/version-checker/blob/98523ab27eee75e9e25fef5cf220d37d108e3ebf/pkg/client/client.go#L16

And add it to the list here.

https://github.com/jetstack/version-checker/blob/98523ab27eee75e9e25fef5cf220d37d108e3ebf/pkg/client/client.go#L80

The first two funcs should be fairly simple to implement, but `RepoImageFromPath` is particularly important for catching edge cases for how registries handle some managed images.

The next is parsing the list reply from the registry 

https://github.com/jetstack/version-checker/blob/98523ab27eee75e9e25fef5cf220d37d108e3ebf/pkg/client/gcr/gcr.go#L46

and mapping that to this struct 

https://github.com/jetstack/version-checker/blob/98523ab27eee75e9e25fef5cf220d37d108e3ebf/pkg/api/types.go#L45

We can also support authentication with a secret that is pipped down, but doesn't have to be in the first PR.

Hope this helps :) let me know if you have any questions. I can always pick it up if time is scarce.

**Comment by JoshVanL** [comment]
We can close this now :) 

/close
