### ISSUE TITLE
Helm chart define Namespace

### ISSUE THREAD

**Issue by nonamef** [jetstack/version-checker#184]
Helm chart doesn't define a namespace so 'default' is used. Would be good to define a namespace and have 'version-checker' as the default to the chart. This would be the same as the example provided in **./deploy/yaml**.

**Comment by hawksight** [comment]
Hey @nonamef thank you for raising the issue. I think that this can be solved with some better documentation in our readme.

You should be able to install this into your own namespace already. For example to install into "version-checker" namespace, you can try:

```shell
helm install version-checker jetstack/version-checker --namespace version-checker --create-namespace
```

**Comment by hawksight** [comment]
We are going to close this out as it currently works. eg, this also works if you want a custom namespace:

```shell
helm install version-checker jetstack/version-checker --namespace monitoring --create-namespace
```

If you have a specific reason to include `namespace: {{ .Release.namespace }}` in all the templates, please let us know.
