### ISSUE TITLE
Support Azure image registry

### ISSUE THREAD

**Issue by JoshVanL** [jetstack/version-checker#22]

**Comment by kutsyk-neocles** [comment]
Hey how to connect ACR to version checker?

**Comment by JoshVanL** [comment]
Hey @kutsyk-neocles, could you go into a bit more detail? This should work out the box.

Are you seeing any errors from the logs?

**Comment by kutsyk-neocles** [comment]
Hey, @JoshVanL we succeeded to configure it after breaking and seeing logs on how to configure it. I would recommend include help output into Readme, which will help understand how to use it better.
