### ISSUE TITLE
Helm Values comment for GHCR refers to Google Aritfactory

### ISSUE THREAD

**Issue by mcsmgs** [jetstack/version-checker#222]
The current chart release (v0.6.0) values.yaml file refers to Google Artifact Registry under the. section meant to describe Github Container registry. https://github.com/jetstack/version-checker/blob/828de950e575b20fc64e8eac779c6c1c2c6fc413/deploy/charts/version-checker/values.yaml#L84

**Comment by davidcollom** [comment]
This is resolved in 0.7.0 which was released a few minutes ago.
