### ISSUE TITLE
Add to helm repo/hub

### ISSUE THREAD

**Issue by Whyeasy** [jetstack/version-checker#49]
Hi,

Currently it's not easy to use this chart with the [helm-operator](https://github.com/fluxcd/helm-operator).
With the helm-operator you can either specify a Helm repo/hub or a git repo.

The git repo one is only safe to use with tags/branches as I don't want it linked with the master 😄. 

I would like to contribute to the chart but this means the chart version/release won't be in sync with the app version. Which will result that the git repo tag approach is not useable anymore.

Adding the chart to https://charts.jetstack.io would solve this issue or use the [chart-releaser](https://github.com/helm/chart-releaser)? This will also result in an easier distribution of the chart 😃

**Comment by chap-dr** [comment]
Hi... Just wanted to comment here and say that ~2 years later this is still something that would be nice to have. :) 

If I can contribute to this in anyway let me know! 😄

**Comment by davidcollom** [comment]
I've raised a [PR](https://github.com/jetstack/jetstack-charts/pull/180/files) to add version-checker v0.2.3 to the jetstack helmcharts repo.

Once merged you should be able to install by:
```bash
$ helm repo add jetstack https://charts.jetstack.io
"jetstack" has been added to your repositories
$ helm install jetstack/version-checker
```

**Comment by davidcollom** [comment]
I will also be looking into getting this into a Github Action to further streamline additional versions

**Comment by davidcollom** [comment]
github actions now automate the release of the helm chart to the `charts.jetstack.io` repository.
