### ISSUE TITLE
Wrong EnableAnnotationKey name in message and options

### ISSUE THREAD

**Issue by yogeek** [jetstack/version-checker#63]
Hello,

When I start version-checker, the log indicates that the annotation to enable the check is `enable.version-checker/${my-container}` :
```
version-checker-6477448bf-4lvvn 
version-checker time="2020-11-20T18:08:42Z" 
level=info 
msg="flag --test-all-containers=false only containers with the annotation \"enable.version-checker/${my-container}=true\" will be parsed"
```

But in the [documentation](https://github.com/jetstack/version-checker/blob/8f26f825bb/README.md#options) and in the [code](https://github.com/jetstack/version-checker/blob/8f26f825bb1a61ccf9498574160d600bdeddc7e8/pkg/api/types.go#L11) the annotation prefix is `enable.version-checker.io`

The `.io` is missing in the log message [here](https://github.com/jetstack/version-checker/blob/f255ab0ce5f0c4a6f4c89f1ccc7c1b6126907288/cmd/app/app.go#L69-L72) and also in options message [here](https://github.com/jetstack/version-checker/blob/9bfbe1d4ba13fd282a01c43011e8de62f555654b/cmd/app/options.go#L99), isn't it ?

**Comment by paulwilljones** [comment]
Resolved in #101
