### ISSUE TITLE
Wrong url path for token in selfhosted client

### ISSUE THREAD

**Issue by kashtan404** [jetstack/version-checker#65]
Hello,

I deployed version-checker with enabled self hosted registry (artifactory), but I got 405 error in the log (sensitive info replaced with stars):
`error: failed to setup image registry clients: failed to create selfhosted client "https://*****": failed to setup token auth (405): {
  "errors" : [ {
    "status" : 405,
    "message" : "Method Not Allowed"
  } ]
}`

It seems that selfhosted client in the version-checker has wrong token url path for artifactory because in [official documentation](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-CreateToken) it is different.

I tested it with curl and got the same result:
`$ curl -u*** -XPOST "https://***/v2/token" -d "username=***"`
`{
  "errors" : [ {
    "status" : 405,
    "message" : "Method Not Allowed"
  } ]
}`

With correct url path it works:
`$ curl -u*** -XPOST "https://***/artifactory/api/security/token" -d "username=***"`
`{
  "scope" : "applied-permissions/groups:*** api:*",
  "access_token" : "***",
  "expires_in" : 3600,
  "token_type" : "Bearer"
}`

**Comment by JoshVanL** [comment]
Thanks @kashtan404,

Is this using a selfhosted instance of Jfrog, or the cloud hosted solution?

**Comment by kashtan404** [comment]
Hi @JoshVanL,
It's self-hosted instance of Jfrog.

**Comment by theodore86** [comment]
@kashtan404 did you manage to integrate the JFrog Artifactory with the version checker?

**Comment by davidcollom** [comment]
#100 should have taken care of the issue you were seeing with regard to security token etc.

If this is still outstanding, please provide us with any additional logs and version of your Jfrog Artifactory so that we can reproduce the issue again.

**Comment by anchaljain30** [comment]
I am getting the same error accessing our self-hosted jfrog artifactory. Could someone help with what worked for them?
@kashtan404

**Comment by anchaljain30** [comment]
```
Error: failed to setup image registry clients: failed to create selfhosted client "https://****/": failed to setup token auth (405): {
  "errors" : [ {
    "status" : 405,
    "message" : "Method Not Allowed"
  } ]
}
```
Using   quay.io/jetstack/version-checker:v0.9.0
