### ISSUE TITLE
Enable Registries with certificates signed by custom authorities.

### ISSUE THREAD

**Issue by zbindenren** [jetstack/version-checker#72]
We use an on premise registry (artifactory), with certificates signed by our private authority. When we try to run version-checker, we get `certificate signed by unknown authority` errors:

```
time="2021-01-18T12:48:29Z" level=error msg="error syncing 'version-checker-597b645b-mpw6b/kube-version-checker': failed to sync pod version-checker-597b645b-mpw6b/kube-version-checker: failed to check container image \"version-checker\": failed to get tags from remote registry for \"quay-docker-remote.repo.example.com/jetstack/version-checker\": failed to get docker image: Get \"https://quay-docker-remote.repo.example.com/v2/jetstack/version-checker/tags/list?n=500\": x509: certificate signed by unknown authority, requeuing" module=controller
```

It would be great to add a flag like `--ca=path/to/truststore.pem` which configures go's transport.

**Comment by davidcollom** [comment]
This is now available from [v0.2.5](https://github.com/jetstack/version-checker/releases/tag/v0.2.5) and onwards for selfHosted repositories.
