### ISSUE TITLE
Support existing secrets

### ISSUE THREAD

**Issue by larsrnielsen** [jetstack/version-checker#75]
I would like avoid storing my username/password in values.yaml and reuse an existing secret for my Artifactory server. An an example of a selfHosted configuration:

```
 - name: something
   url: something
   # username
   # password
   # token
   secretRef: something
```

My use case is that I use external-secrets for integration with AWS Secrets Manager and to avoid storing clear text passwords in GitHub.

**Comment by davidcollom** [comment]
I agree, and think this would be a great addition!
