### ISSUE TITLE
Add kubernetes probes support

### ISSUE THREAD

**Issue by psibi** [jetstack/version-checker#78]
From looking at the deployment manifest, it currently doesn't seem to have any probes for readiness or liveness check. 

It would be nice to get that fixed.

**Comment by RobertWRoss** [comment]
time="2023-04-15T09:59:48Z" level=debug msg="image is not latest docker.io/istio/proxyv2: 1.11.4 -> 1.17.2" container=istio-proxy module=controller
 name=tst-gh-int82-xfr-dispatch-656c66454-tj47x namespace=tst-gh
time="2023-04-15T09:59:48Z" level=error msg="error syncing 'tst-gh-int82-xfr-dispatch-656c66454-tj47x/tst-gh':
 failed to sync pod tst-gh-int82-xfr-dispatch-656c66454-tj47x/tst-gh: failed to check container image \"int82-xfr-dispatch\":
 failed to get tags from remote registry for \"ol8-tst-k8s-master-node.com:5000/int82-xfr-dispatch\": failed to get docker image:
 Get \"https://ol8-tst-k8s-master-node.gcp.itemate.com:5000/v2/int82-xfr-dispatch/tags/list?n=500\": x509: certificate signed by unknown authority, 
 requeuing" module=controller
 
 curl -k -u docker_reg:0IFmcttx00 https://ol8-tst-k8s-master-node.com:5000/v2/int82-xfr-dispatch/tags/list?n=5000
{"name":"int82-xfr-dispatch","tags":["tst-bj-20211102-J11-237-1183f99c","tst-gh-20211117-J13-240-c3f64612"
 
       version-checker
    Args:
      --test-all-containers
      --selfhosted-username=docker_reg
      --selfhosted-password=0IFmcttx00
      --insecure-skip-tls-verify=true
      --log-level=debug

This is the Error that I am getting in the log file.
How are you calling the versions. What do I need to add to my config
