### ISSUE TITLE
Is this project still active? Container Image update?

### ISSUE THREAD

**Issue by Matthiator** [jetstack/version-checker#88]
Is this project still under maintenance?
I really like the project, however:
The image quay.io/jetstack/version-checker:v0.2.1 is now over 2 years old and has some security issues: https://trivy.dev/results/?image=quay.io/jetstack/version-checker:v0.2.1

I built a new image with alpine:3.17.1. Unfortunately, Trivy still finds some security issues regarding gobinary:

![grafik](https://user-images.githubusercontent.com/33330325/215333503-c274c3ae-74c1-4384-b650-02108759aad4.png)

Would it be possible for someone to build an up-to-date container image without any security issues?

**Comment by davidcollom** [comment]
Hi @Matthiator, Thanks for bringing this to our attention. Unfortunately, version-checker hasn't been given the love and attention that it deserves.

I have all intentions of getting this project back on track however I've not had time to sit down and get things back up and running due to other commitments.

PR's are as always welcome if you have the time/experience.

**Comment by mboeren** [comment]
Would love it if this got revived. It does exactly what I'm looking for, nothing more, nothing less.

**Comment by whiskeysierra** [comment]
@davidcollom I opened a PR. Getting that in and publishing a new release would be much appreciated.

**Comment by davidcollom** [comment]
I've created a 0.2.2 release yesterday and in the [process of getting the helm chart](https://github.com/jetstack/jetstack-charts/pull/180) published to our helm repo.

**Comment by davidcollom** [comment]
You can now pull and use the Jetstack Helm Chart Repo to install `version-checker` 🎉 

```sh
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm search repo jetstack
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION                                       
jetstack/cert-manager                   v1.12.2         v1.12.2         A Helm chart for cert-manager                     
jetstack/cert-manager-approver-policy   v0.7.0          v0.7.0          A Helm chart for cert-manager-approver-policy     
jetstack/cert-manager-csi-driver        v0.5.0          v0.5.0          A Helm chart for cert-manager-csi-driver          
jetstack/cert-manager-csi-driver-spiffe v0.4.0          v0.4.0          cert-manager csi-driver-spiffe is a CSI plugin ...
jetstack/cert-manager-google-cas-issuer v0.6.2          v0.6.2          A Helm chart for jetstack/google-cas-issuer       
jetstack/cert-manager-istio-csr         v0.7.0          v0.7.0          istio-csr enables the use of cert-manager for i...
jetstack/cert-manager-trust             v0.2.1          v0.2.0          DEPRECATED: The old name for trust-manager. Use...
jetstack/trust-manager                  v0.5.0          v0.5.0          trust-manager is the easiest way to manage TLS ...
jetstack/version-checker                0.2.3           v0.2.2          A Helm chart for version-checker                  
```
